# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b68835b9b9a98fc163bd5646717cbbe943de099277daf45f2d43c648121d8b7714a23421422d0ccfe204ea81cff354ff441ead5f6ed4103712b8b7089bdae24

test:
  secret_key_base: c0f5df7675474a9a764f04fb04a59111abadd43b4f559c1fce9b54f2cb84ff001fbccefa77b3f9b85ff8a652cc1be95eb24f99cb5f81718eebcbcd6f00e99862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
